using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using ArknoNights.Battle.Core;
namespace ArknoNights.Battle.Presentation
{
public enum UnitPresentationAction { Idle, Move, Attack, Death }
public sealed class BattlePresentationCompressionMetrics { internal BattlePresentationCompressionMetrics(int originalMoveCount,int positionKeyCount,double maximumErrorUnits){OriginalMoveCount=originalMoveCount;PositionKeyCount=positionKeyCount;CompressionRatio=originalMoveCount==0?1d:(double)positionKeyCount/originalMoveCount;MaximumErrorUnits=maximumErrorUnits;} public int OriginalMoveCount{get;} public int PositionKeyCount{get;} public double CompressionRatio{get;} public double MaximumErrorUnits{get;} }
public readonly struct PresentationPosition { public PresentationPosition(double x,double y){XUnits=x;YUnits=y;} public double XUnits{get;} public double YUnits{get;} }
public readonly struct UnitPresentationSample { internal UnitPresentationSample(bool s,bool a,PresentationPosition p,int f,UnitPresentationAction action,int start,int seq,float mult,int max,int hp,int shield){HasSpawned=s;IsAlive=a;ShouldDisplay=s;Position=p;HorizontalFacing=f;Action=action;ActionStartTick=start;ActionSequence=seq;AttackAnimationSpeedMultiplier=mult;MaxHitPoints=max;CurrentHitPoints=hp;CurrentShield=shield;} public bool HasSpawned{get;} public bool IsAlive{get;} public bool ShouldDisplay{get;} public PresentationPosition Position{get;} public int HorizontalFacing{get;} public UnitPresentationAction Action{get;} public int ActionStartTick{get;} public int ActionSequence{get;} public float AttackAnimationSpeedMultiplier{get;} public int MaxHitPoints{get;} public int CurrentHitPoints{get;} public int CurrentShield{get;} }
public sealed class UnitPresentationTrack
{
internal readonly struct PositionSegment { public PositionSegment(int s,int e,FixedPosition f,FixedPosition t){Start=s;End=e;From=f;To=t;} public int Start{get;} public int End{get;} public FixedPosition From{get;} public FixedPosition To{get;} }
internal readonly struct HpKey { public HpKey(int t,int s,int v){Tick=t;Sequence=s;Value=v;} public int Tick{get;} public int Sequence{get;} public int Value{get;} }
internal readonly struct Attack { public Attack(int t,int s,int d,float m){Tick=t;Sequence=s;Duration=d;Multiplier=m;} public int Tick{get;} public int Sequence{get;} public int Duration{get;} public float Multiplier{get;} }
private readonly IReadOnlyList<PositionSegment> positions; private readonly IReadOnlyList<HpKey> hp; private readonly IReadOnlyList<Attack> attacks; private readonly int endTick; private readonly int shield;
internal UnitPresentationTrack(BattleUnitInstanceSnapshot x,int spawn,int end,int? death,IEnumerable<PositionSegment> p,IEnumerable<HpKey> h,IEnumerable<Attack> a){UnitId=x.UnitId;TypeId=x.TypeId;Side=x.Side;EliteLevel=x.EliteLevel;SpawnTick=spawn;DeathTick=death;MaxHitPoints=x.MaxHitPoints;endTick=end;shield=x.CurrentShield;positions=new ReadOnlyCollection<PositionSegment>(p.ToArray());hp=new ReadOnlyCollection<HpKey>(h.ToArray());attacks=new ReadOnlyCollection<Attack>(a.ToArray());}
public string UnitId{get;} public string TypeId{get;} public BattleSide Side{get;} public int EliteLevel{get;} public int SpawnTick{get;} public int? DeathTick{get;} public int MaxHitPoints{get;}
public UnitPresentationSample Sample(double tick){if(tick<SpawnTick)return new UnitPresentationSample(false,false,new PresentationPosition(0,0),1,UnitPresentationAction.Idle,SpawnTick,0,1,MaxHitPoints,0,shield);tick=Math.Min(tick,endTick);var activePositions=positions.Where(x=>tick>=x.Start&&tick<=x.End).OrderByDescending(x=>x.Start).ToArray();var p=activePositions.Length>0?activePositions[0]:positions.Where(x=>x.End<=tick).OrderByDescending(x=>x.End).First();var d=Math.Max(1,p.End-p.Start);var r=Math.Max(0,Math.Min(1,(tick-p.Start)/d));var pos=new PresentationPosition((p.From.XUnits+(p.To.XUnits-p.From.XUnits)*r)/100d,(p.From.YUnits+(p.To.YUnits-p.From.YUnits)*r)/100d);var alive=!DeathTick.HasValue||tick<DeathTick.Value;var action=UnitPresentationAction.Idle;var start=SpawnTick;var seq=0;var mult=1f;if(!alive){action=UnitPresentationAction.Death;start=DeathTick.Value;}else{var at=attacks.Where(x=>tick>=x.Tick&&tick<x.Tick+x.Duration).OrderByDescending(x=>x.Tick).ThenByDescending(x=>x.Sequence).FirstOrDefault();if(at.Duration>0){action=UnitPresentationAction.Attack;start=at.Tick;seq=at.Sequence;mult=at.Multiplier;}else if(p.End>p.Start&&tick>=p.Start&&tick<=p.End)action=UnitPresentationAction.Move;}var current=hp.Where(x=>tick>=x.Tick).OrderBy(x=>x.Tick).ThenBy(x=>x.Sequence).Last().Value;var facing=positions.Where(x=>tick>=x.Start&&x.To.XUnits!=x.From.XUnits).Select(x=>x.To.XUnits<x.From.XUnits?-1:1).DefaultIfEmpty(1).Last();return new UnitPresentationSample(true,alive,pos,facing,action,start,seq,mult,MaxHitPoints,current,shield);}
internal FixedPosition FinalPosition=>positions.Last().To; internal int FinalHitPoints=>hp.Last().Value; internal bool FinalAlive=>!DeathTick.HasValue;
}
public sealed class BattlePresentationTrack
{
private readonly IReadOnlyList<UnitPresentationTrack> units; private readonly Dictionary<string,UnitPresentationTrack> lookup;
internal BattlePresentationTrack(BattleRunResult r,IEnumerable<UnitPresentationTrack> u,string events,BattlePresentationCompressionMetrics metrics){BattleId=r.BattleId;HomePlayerId=r.HomePlayerId;AwayPlayerId=r.AwayPlayerId;EndTick=r.CompletedTicks;Winner=r.Winner;StopReason=r.StopReason;units=new ReadOnlyCollection<UnitPresentationTrack>(u.ToArray());lookup=units.ToDictionary(x=>x.UnitId,StringComparer.Ordinal);SourceInputDigest=Digest(r.InputCanonicalSummary);SourceEventDigest=events;SourceResultDigest=Digest(r.StableSummary);CompressionMetrics=metrics??new BattlePresentationCompressionMetrics(0,0,0d);StableSummary=Digest(BattleId+SourceInputDigest+events+SourceResultDigest+CompressionMetrics.OriginalMoveCount+":"+CompressionMetrics.PositionKeyCount+":"+CompressionMetrics.CompressionRatio.ToString("R",System.Globalization.CultureInfo.InvariantCulture)+":"+CompressionMetrics.MaximumErrorUnits.ToString("R",System.Globalization.CultureInfo.InvariantCulture));}
public string BattleId{get;} public string HomePlayerId{get;} public string AwayPlayerId{get;} public int EndTick{get;} public BattleSide? Winner{get;} public BattleStopReason StopReason{get;} public IReadOnlyList<UnitPresentationTrack> Units=>units; public string SourceInputDigest{get;} public string SourceEventDigest{get;} public string SourceResultDigest{get;} public BattlePresentationCompressionMetrics CompressionMetrics{get;} public string StableSummary{get;} public bool TryGetUnit(string id,out UnitPresentationTrack t)=>lookup.TryGetValue(id??string.Empty,out t); internal static string Digest(string s){unchecked{uint h=2166136261;foreach(var c in s??string.Empty){h^=c;h*=16777619;}return h.ToString("X8");}}
}
}
